version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instagram
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: postgres

  redis:
    image: redis:8.2.1
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: